@startuml Library

class "Book" {
    +ISBN : Int <<PK>>
    publicationYear : Date
    +author : String
    numberOfPages : Int
}

class "BookCopy" {
    +copyID : Int <<PK>>
    +shelfLocation : Int
    +ISBN : Int <<PK, FK>>
}

class "Reader" {
    +readerID : Int <<PK>>
    firstName : String
    lastName : String
    birthday : Date
}

class "Publisher" {
    +name : String <<PK>>
    +address : String
}

class "Borrowing" {
    +readerID : Int <<PK, FK>>
    +copyID : Int <<PK, FK>>
    +returnDate : Date
}

class "Category" {
    +name : String <<PK>>
    +parentID : Int <<FK>>
}

Publisher }|--o{ Book : publishes
Book ||--o{ BookCopy
Reader ||--o{ Borrowing
Borrowing }o--|| BookCopy
Category |o--o{ Category : has subcategory
Book }o--|| Category

@enduml